### ISSUE TITLE
The 1.15.+ Roadmap

### ISSUE THREAD

**Issue by Sollace** [MineLittlePony/MineLittlePony#106]
This is going to be the roadmap of things planned for the next release of Mine Little Pony, either a 1.12 patch update, or 1.13 when that eventually becomes a thing.

If there's any details I miss, or that we need to add, put them in a comment below and I'll amend this issue!

# Skinning

- [x] Skinning is to be changed entirely in 1.13. We'll be dropping a lot of support for the mojang skins servers in favour of using using our own ones exclusively. This is to allow for a new template to make skinning easier and more flexible, with a cleaner, more sensible layout, and plenty of space to support all the individual components of the pony models.

<div align="center">
<img src="https://cdn.discordapp.com/attachments/280051170242854912/504995906916188160/unknown.png">
<br>
(example mockup - things may change)
<br>
<br>
</div>

- [ ] All wearables are to be customisable by uploading a separate texture, similar to how capes and elytra currently work.
- [ ] An interface for viewing past skins uploaded to a given server and for switching between them.
- [x] <s>Trigger pixels and wearables are to be moved to json metadata uploaded to the skin server alongside texture files</s> (cancelled)

# Technical

- [x] Change the versioning scheme
        We need to stop putting the minecraft version in the version for the mod and just version ourselves normally. I get why it's there, but it's completely unnecessary when you have the minecraft version in the filename already.
- [x] Break the project up into separate components.
  - [x] HDSkins is to be extracted to its own github repository and maintained as a separate mod.
  - [x] MineLittlePony itself is to be separate into a Client and Library component, the latter of which being available for mods to load as a dependency either on the client or server.
 - [x] Merge Big Pony into the mod proper (will this be an issue with Hypixel?)

# 1.13 Stuff

- [x] Update to 1.13.x (duh)
- [x] Implement pony models for the Drown'd and other Aquatic beasts (suggestions will be opened closer to the time)

**Comment by killjoy1221** [comment]
https://github.com/MineLittlePony/HDSkins

**Comment by Sollace** [comment]
@killjoy1221 Nice!

Too bad we can't use that until we have a LiteLoader version. :T

**Comment by Sollace** [comment]
@killjoy1221 Unmarking the hdskins as done, because as previously mentioned, this is basically useless to us as a forge mod.

**Comment by Sollace** [comment]
Stale.
